# Generated by Django 2.1.8 on 2019-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='api_calls_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
