# Generated by Django 2.1.8 on 2019-06-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_api_calls_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_item_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
