# Generated by Django 2.1.8 on 2019-06-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_subscription_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Small Business', 'sb'), ('Enterprise', 'ent'), ('Professional', 'pro')], default='Free', max_length=30),
        ),
    ]
