# Generated by Django 2.1.8 on 2019-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20190618_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Small Business', 'sb'), ('Enterprise', 'ent'), ('Professional', 'pro'), ('Free', 'free'), ('', '')], default='Free', max_length=30, null=True),
        ),
    ]
