# Generated by Django 2.1.8 on 2019-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20190619_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='remaining_api_calls',
            field=models.IntegerField(default=0),
        ),
    ]
