# Generated by Django 2.1.8 on 2019-06-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
    ]
