# Generated by Django 2.1.8 on 2019-06-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=15),
        ),
    ]
