# Generated by Django 2.1.8 on 2019-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
