# Generated by Django 2.1.8 on 2019-06-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='response',
            new_name='device',
        ),
    ]
